### ISSUE TITLE
Female Seawolf Eye path are incorrect for Asymeyes

### ISSUE THREAD

**Issue by luxiel** [Sebane1/FFXIVLooseTextureCompiler#1]
Paths for Asymeyes textures for Seawolf Female are pathing to "roegadyn_seawolVES_female.tex", but should path to "roegadyn_seawolF_female.tex" on the mod package generated by LTC.

Probably related to the clan name inside RaceInfo.cs.

Also, there is a typo for Hellsguard inside the same file (it reads "Hellsgaurd"), which will most likely result in similar problems for that clan.

**Comment by Sebane1** [comment]
This will be corrected soon.
