### ISSUE TITLE
Male seeker eye issue

### ISSUE THREAD

**Issue by Kirishikki** [Sebane1/FFXIVLooseTextureCompiler#11]
When creating eye mod and selecting masculine seeker eye. It changes nothing in game and changed items says, customization unknown.

**Comment by Sebane1** [comment]
Looks like this was caused by me re-ordering lalafells. Forgot to re-order the eye paths too.

**Comment by Kirishikki** [comment]
It appears as though highlander female face 4 also has this issue. im very
sorry if im bothering too much. im happy to stop if its obnoxious >.<

**Comment by Sebane1** [comment]
Unreported bugs don't get fixed, so its not a problem.
(just means somebody else gets to suffer with the same issue, when I am not aware)

**Comment by Sebane1** [comment]
This should now be resolved in v2.0.2.2
