### ISSUE TITLE
[Feature Request] Add smooth/buff options for Bibo

### ISSUE THREAD

**Issue by LoAndEvolve** [Sebane1/FFXIVLooseTextureCompiler#2]
Would love this as an option unless I missed a setting somewhere? Thank you so much for the tool though! Saves me so much time.

**Comment by Sebane1** [comment]
I've been trying to come up with an elegant way of allowing users to provide their own underlay textures to the tool.
I think in general I stuck with default options for the average user, and to try and keep the size of the tool down.

There "is" a less intuitive way to go about replacing these underlay texture manually.
"/res/textures" in the tools folder will have multiple body textures in a format called .ltct
Mostly a custom format for keeping the file size down, and to prevent involuntary sight of the textures.

Under "Tools -> Dev Tools" there's several options for converting these files back to .png or converting .png to this format.
You could then try replacing the textures Loose Texture Compiler is using in the relevant folders.

Of course, this will globally affect every future project created with the tool.

**Comment by Sebane1** [comment]
I've finally added an elegant built in solution for this.
