### ISSUE TITLE
[Feature Request] Add Support for Asymmetrical Vanilla Bodies

### ISSUE THREAD

**Issue by haysidney** [Sebane1/FFXIVLooseTextureCompiler#3]
Could you add support for Asymmetrical Vanilla Bodies? It'd be great to use Loose Texture Compiler to convert BIBO textures to Asymmetrical Vanilla textures and whatnot!

https://www.glamourdresser.com/mods/aysmm-vanilla-bodies-for-everyone

**Comment by Sebane1** [comment]
Loose Texture Compiler indirectly already supports it.
Asym Vanilla Bodies uses Bibo+ pathing (and the UV's are basically the same)

Which is to say, Asym Vanilla Bodies is just Bibo+ and TBSE with a vanilla body.

There's also Atramentum Luminis which makes all vanilla gear (and bodies) Bibo+/TBSE compatible through shader magic.
https://www.xivmodarchive.com/modid/68013
