### ISSUE TITLE
"Enable Universal Compatibility" doesn't respect input resolution

### ISSUE THREAD

**Issue by sadtaco** [Sebane1/FFXIVLooseTextureCompiler#4]
Inputting 4k or 2k textures from Bibo+ with this enabled results in 1k output to the other formats. I can not find any other options that might result in getting a 4k or similar output to the others.

Similarly, glow seems to not be DXT5 output. That channel seems to be posterized or something.

**Comment by Sebane1** [comment]
Do you have the full version of Loose Texture Compiler downloaded?
4k should be the baseline.

**Comment by sadtaco** [comment]
I had gotten it from https://github.com/Sebane1/FFXIVLooseTextureCompiler/releases yes. Is there a setting somewhere that I'm missing?
The Bibo textures I'm importing at 4k are 4k, but the other ones it makes are not.

edit: with the latest version, it output to 4k fine. Maybe it was that I didn't have enough free memory before, too.
