### ISSUE TITLE
doesnt convert from bibo to gen 3 correctly

### ISSUE THREAD

**Issue by Ainokami7** [Sebane1/FFXIVLooseTextureCompiler#6]
When I convert from bibo+ to gen 3, the textures for my scales and tattoos dont line up properly

**Comment by Sebane1** [comment]
This is an XNormal limitation. Texture seams are unavoidable in some areas. Especially where joints connect such as shoulders or parts of the waist.

**Comment by Ainokami7** [comment]
yeah its not just seams, the majority of the texture becomes misaligned slightly so the scale texture doesn't go on the scales properly which is a shame

**Comment by Sebane1** [comment]
Can you show some visual examples on what it precisely looks like?

**Comment by Ainokami7** [comment]
![scales gen 3](https://github.com/Sebane1/FFXIVLooseTextureCompiler/assets/141505294/fdae76f2-040d-4286-a9d3-43de6f2db7a8)
![Aino scales gen 3 conversation](https://github.com/Sebane1/FFXIVLooseTextureCompiler/assets/141505294/ecb37aaa-339c-4199-864d-ac1080c521fd)

this might be the best way I could show you how it converts. one pic is my normal gen 3 skin texture with my scales, and the other is just my scales with how this converters them to when i go from bibo to gen 3, on top of the first picture for a close comparison
